name: Create Release

on:
  push:
    tags:
      - 'v*' # 当推送以 'v' 开头的标签时触发

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile the C program
      run: |
        gcc -o hello-release main.c

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body: "This is a release of the hello-release program."
        files: |
          hello-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}